"""service order intake, triage, tasks and SLA fields"""
from alembic import op
import sqlalchemy as sa
revision="f2c3d4e5a601"; down_revision="e1b6c7d8f902"; branch_labels=None; depends_on=None
def upgrade():
    with op.batch_alter_table("service_orders") as b:
        for name,typ in (("contact_id",sa.String(36)),("address_id",sa.String(36)),("conversation_id",sa.String(36)),("channel_of_origin",sa.String(32)),("service_type",sa.String(20)),("team_id",sa.String(36)),("responsible_id",sa.String(36)),("technician_id",sa.String(36)),("sla_policy",sa.JSON),("sla_due_at",sa.DateTime(timezone=True)),("sla_paused_at",sa.DateTime(timezone=True)),("received_at",sa.DateTime(timezone=True)),("triaged_at",sa.DateTime(timezone=True)),("completed_at",sa.DateTime(timezone=True)),("internal_notes",sa.Text),("public_notes",sa.Text)):
            b.add_column(sa.Column(name,typ,server_default="{}" if name=="sla_policy" else ("bench" if name=="service_type" else None),nullable=False if name in {"service_type","sla_policy"} else True))
        b.create_foreign_key("fk_service_orders_contact_id_contacts","customer_contacts",["contact_id"],["id"]); b.create_foreign_key("fk_service_orders_address_id_addresses","customer_addresses",["address_id"],["id"]); b.create_foreign_key("fk_service_orders_conversation_id_conversations","conversations",["conversation_id"],["id"]); b.create_foreign_key("fk_service_orders_team_id_teams","teams",["team_id"],["id"]); b.create_foreign_key("fk_service_orders_responsible_id_users","users",["responsible_id"],["id"]); b.create_foreign_key("fk_service_orders_technician_id_users","users",["technician_id"],["id"])
    for col in ("contact_id","address_id","conversation_id","team_id","responsible_id","technician_id","sla_due_at"): op.create_index(f"ix_service_orders_{col}","service_orders",[col])
    op.create_table("service_order_tasks",sa.Column("id",sa.String(36),primary_key=True),sa.Column("company_id",sa.String(36),sa.ForeignKey("companies.id"),nullable=False),sa.Column("service_order_id",sa.String(36),sa.ForeignKey("service_orders.id",ondelete="CASCADE"),nullable=False),sa.Column("title",sa.String(200),nullable=False),sa.Column("description",sa.Text),sa.Column("assigned_to",sa.String(36),sa.ForeignKey("users.id")),sa.Column("status",sa.String(20),nullable=False),sa.Column("priority",sa.String(20),nullable=False),sa.Column("due_at",sa.DateTime(timezone=True)),sa.Column("completed_at",sa.DateTime(timezone=True)),sa.Column("blocked_reason",sa.Text),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False))
    for col in ("company_id","service_order_id","assigned_to","status"): op.create_index(f"ix_service_order_tasks_{col}","service_order_tasks",[col])
    op.create_table("service_order_triage",sa.Column("id",sa.String(36),primary_key=True),sa.Column("company_id",sa.String(36),sa.ForeignKey("companies.id"),nullable=False),sa.Column("service_order_id",sa.String(36),sa.ForeignKey("service_orders.id",ondelete="CASCADE"),nullable=False,unique=True),sa.Column("performed_by",sa.String(36),sa.ForeignKey("users.id"),nullable=False),sa.Column("physical_condition",sa.Text),sa.Column("visual_signs",sa.Text),sa.Column("powers_on",sa.Boolean),sa.Column("accessories",sa.JSON,nullable=False),sa.Column("electrical_risk",sa.Boolean,nullable=False),sa.Column("mechanical_risk",sa.Boolean,nullable=False),sa.Column("suggested_priority",sa.String(20)),sa.Column("observations",sa.Text),sa.Column("checklist",sa.JSON,nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False))
    op.create_index("ix_service_order_triage_company_id","service_order_triage",["company_id"])
def downgrade():
    op.drop_index("ix_service_order_triage_company_id",table_name="service_order_triage");op.drop_table("service_order_triage")
    for col in ("company_id","service_order_id","assigned_to","status"): op.drop_index(f"ix_service_order_tasks_{col}",table_name="service_order_tasks")
    op.drop_table("service_order_tasks")
    for col in ("contact_id","address_id","conversation_id","team_id","responsible_id","technician_id","sla_due_at"): op.drop_index(f"ix_service_orders_{col}",table_name="service_orders")
    with op.batch_alter_table("service_orders") as b:
        for name in ("fk_service_orders_contact_id_contacts","fk_service_orders_address_id_addresses","fk_service_orders_conversation_id_conversations","fk_service_orders_team_id_teams","fk_service_orders_responsible_id_users","fk_service_orders_technician_id_users"):
            try:b.drop_constraint(name,type_="foreignkey")
            except Exception:pass
        for col in ("public_notes","internal_notes","completed_at","triaged_at","received_at","sla_paused_at","sla_due_at","sla_policy","technician_id","responsible_id","team_id","service_type","channel_of_origin","conversation_id","address_id","contact_id"):b.drop_column(col)
