"""diagnoses, technical tests, measurements and checklists"""
from alembic import op
import sqlalchemy as sa
revision="g3d4e5f6a702";down_revision="f2c3d4e5a601";branch_labels=None;depends_on=None
def upgrade():
    op.create_table("service_order_diagnoses",sa.Column("id",sa.String(36),primary_key=True),sa.Column("company_id",sa.String(36),sa.ForeignKey("companies.id"),nullable=False),sa.Column("service_order_id",sa.String(36),sa.ForeignKey("service_orders.id",ondelete="CASCADE"),nullable=False),sa.Column("version",sa.Integer,nullable=False),sa.Column("summary",sa.Text,nullable=False),sa.Column("details",sa.Text),sa.Column("risk",sa.String(40)),sa.Column("repairable",sa.Boolean),sa.Column("recommendation",sa.Text),sa.Column("status",sa.String(20),nullable=False),sa.Column("technician_id",sa.String(36),sa.ForeignKey("users.id"),nullable=False),sa.Column("reviewer_id",sa.String(36),sa.ForeignKey("users.id")),sa.Column("reviewed_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False),sa.UniqueConstraint("service_order_id","version"),sa.CheckConstraint("status IN ('draft','under_review','approved','rejected','superseded')",name="diagnosis_status"))
    for table in ("service_order_diagnoses",):
        for col in ("company_id","service_order_id","status"):op.create_index(f"ix_{table}_{col}",table,[col])
    op.create_table("service_order_measurements",sa.Column("id",sa.String(36),primary_key=True),sa.Column("company_id",sa.String(36),sa.ForeignKey("companies.id"),nullable=False),sa.Column("service_order_id",sa.String(36),sa.ForeignKey("service_orders.id",ondelete="CASCADE"),nullable=False),sa.Column("parameter",sa.String(120),nullable=False),sa.Column("value",sa.String(120),nullable=False),sa.Column("unit",sa.String(40)),sa.Column("instrument",sa.String(120)),sa.Column("condition",sa.String(200)),sa.Column("result",sa.String(40)),sa.Column("performed_by",sa.String(36),sa.ForeignKey("users.id"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False))
    op.create_index("ix_service_order_measurements_service_order_id","service_order_measurements",["service_order_id"])
    op.create_table("service_order_technical_tests",sa.Column("id",sa.String(36),primary_key=True),sa.Column("company_id",sa.String(36),sa.ForeignKey("companies.id"),nullable=False),sa.Column("service_order_id",sa.String(36),sa.ForeignKey("service_orders.id",ondelete="CASCADE"),nullable=False),sa.Column("name",sa.String(160),nullable=False),sa.Column("procedure",sa.Text),sa.Column("result",sa.Text),sa.Column("status",sa.String(20),nullable=False),sa.Column("observation",sa.Text),sa.Column("performed_by",sa.String(36),sa.ForeignKey("users.id"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False),sa.CheckConstraint("status IN ('passed','failed','inconclusive')",name="technical_test_status"))
    op.create_index("ix_service_order_technical_tests_service_order_id","service_order_technical_tests",["service_order_id"])
    op.create_table("checklist_templates",sa.Column("id",sa.String(36),primary_key=True),sa.Column("company_id",sa.String(36),sa.ForeignKey("companies.id"),nullable=False),sa.Column("name",sa.String(160),nullable=False),sa.Column("purpose",sa.String(120)),sa.Column("status",sa.String(20),nullable=False),sa.Column("version",sa.Integer,nullable=False),sa.Column("items",sa.JSON,nullable=False),sa.Column("created_by",sa.String(36),sa.ForeignKey("users.id"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False))
    op.create_index("ix_checklist_templates_company_id","checklist_templates",["company_id"])
    op.create_table("service_order_checklists",sa.Column("id",sa.String(36),primary_key=True),sa.Column("company_id",sa.String(36),sa.ForeignKey("companies.id"),nullable=False),sa.Column("service_order_id",sa.String(36),sa.ForeignKey("service_orders.id",ondelete="CASCADE"),nullable=False),sa.Column("template_id",sa.String(36),sa.ForeignKey("checklist_templates.id")),sa.Column("template_version",sa.Integer,nullable=False),sa.Column("items",sa.JSON,nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("completed_by",sa.String(36),sa.ForeignKey("users.id")),sa.Column("completed_at",sa.DateTime(timezone=True)))
    for col in ("company_id","service_order_id","status"):op.create_index(f"ix_service_order_checklists_{col}","service_order_checklists",[col])
def downgrade():
    for col in ("company_id","service_order_id","status"):op.drop_index(f"ix_service_order_checklists_{col}",table_name="service_order_checklists")
    op.drop_table("service_order_checklists");op.drop_index("ix_checklist_templates_company_id",table_name="checklist_templates");op.drop_table("checklist_templates");op.drop_index("ix_service_order_technical_tests_service_order_id",table_name="service_order_technical_tests");op.drop_table("service_order_technical_tests");op.drop_index("ix_service_order_measurements_service_order_id",table_name="service_order_measurements");op.drop_table("service_order_measurements")
    for col in ("company_id","service_order_id","status"):op.drop_index(f"ix_service_order_diagnoses_{col}",table_name="service_order_diagnoses")
    op.drop_table("service_order_diagnoses")
