"""service completion, field visits and warranty returns"""
from alembic import op
import sqlalchemy as sa

revision = "h4e5f6a7b803"
down_revision = "g3d4e5f6a702"
branch_labels = None
depends_on = None

def upgrade():
    op.create_table("service_order_work_sessions",
        sa.Column("id", sa.String(36), primary_key=True), sa.Column("company_id", sa.String(36), sa.ForeignKey("companies.id"), nullable=False), sa.Column("service_order_id", sa.String(36), sa.ForeignKey("service_orders.id", ondelete="CASCADE"), nullable=False), sa.Column("mode", sa.String(20), nullable=False), sa.Column("technician_id", sa.String(36), sa.ForeignKey("users.id"), nullable=False), sa.Column("status", sa.String(20), nullable=False, server_default="active"), sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("paused_at", sa.DateTime(timezone=True)), sa.Column("ended_at", sa.DateTime(timezone=True)), sa.Column("result", sa.Text), sa.Column("notes", sa.Text), sa.CheckConstraint("mode IN ('bench','remote','field')", name="work_session_mode"), sa.CheckConstraint("status IN ('active','paused','completed','cancelled')", name="work_session_status"))
    op.create_index("ix_service_order_work_sessions_company_id", "service_order_work_sessions", ["company_id"]); op.create_index("ix_service_order_work_sessions_service_order_id", "service_order_work_sessions", ["service_order_id"])
    op.create_table("service_visits", sa.Column("id", sa.String(36), primary_key=True), sa.Column("company_id", sa.String(36), sa.ForeignKey("companies.id"), nullable=False), sa.Column("service_order_id", sa.String(36), sa.ForeignKey("service_orders.id", ondelete="CASCADE"), nullable=False), sa.Column("technician_id", sa.String(36), sa.ForeignKey("users.id")), sa.Column("address", sa.Text, nullable=False), sa.Column("scheduled_start", sa.DateTime(timezone=True), nullable=False), sa.Column("scheduled_end", sa.DateTime(timezone=True)), sa.Column("status", sa.String(20), nullable=False, server_default="scheduled"), sa.Column("result", sa.Text), sa.Column("notes", sa.Text), sa.CheckConstraint("status IN ('scheduled','confirmed','en_route','on_site','completed','cancelled','no_show','rescheduled')", name="visit_status"))
    op.create_index("ix_service_visits_company_id", "service_visits", ["company_id"]); op.create_index("ix_service_visits_service_order_id", "service_visits", ["service_order_id"]); op.create_index("ix_service_visits_status", "service_visits", ["status"])
    op.create_table("service_order_deliveries", sa.Column("id", sa.String(36), primary_key=True), sa.Column("company_id", sa.String(36), sa.ForeignKey("companies.id"), nullable=False), sa.Column("service_order_id", sa.String(36), sa.ForeignKey("service_orders.id", ondelete="CASCADE"), nullable=False, unique=True), sa.Column("mode", sa.String(20), nullable=False), sa.Column("delivered_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("performed_by", sa.String(36), sa.ForeignKey("users.id"), nullable=False), sa.Column("condition", sa.Text), sa.Column("accessories", sa.JSON, nullable=False, server_default="{}"), sa.Column("notes", sa.Text), sa.CheckConstraint("mode IN ('delivery','pickup')", name="delivery_mode"))
    op.create_table("warranties", sa.Column("id", sa.String(36), primary_key=True), sa.Column("company_id", sa.String(36), sa.ForeignKey("companies.id"), nullable=False), sa.Column("service_order_id", sa.String(36), sa.ForeignKey("service_orders.id", ondelete="CASCADE"), nullable=False, unique=True), sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False), sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False), sa.Column("coverage", sa.Text), sa.Column("exclusions", sa.Text), sa.Column("status", sa.String(20), nullable=False, server_default="active"), sa.Column("created_by", sa.String(36), sa.ForeignKey("users.id"), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_index("ix_warranties_company_id", "warranties", ["company_id"])
    op.create_table("warranty_returns", sa.Column("id", sa.String(36), primary_key=True), sa.Column("company_id", sa.String(36), sa.ForeignKey("companies.id"), nullable=False), sa.Column("original_service_order_id", sa.String(36), sa.ForeignKey("service_orders.id"), nullable=False), sa.Column("return_service_order_id", sa.String(36), sa.ForeignKey("service_orders.id"), nullable=False, unique=True), sa.Column("reason", sa.Text, nullable=False), sa.Column("decision", sa.String(20)), sa.Column("created_by", sa.String(36), sa.ForeignKey("users.id"), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_index("ix_warranty_returns_company_id", "warranty_returns", ["company_id"]); op.create_index("ix_warranty_returns_original_service_order_id", "warranty_returns", ["original_service_order_id"])

def downgrade():
    op.drop_index("ix_warranty_returns_original_service_order_id", table_name="warranty_returns"); op.drop_index("ix_warranty_returns_company_id", table_name="warranty_returns"); op.drop_table("warranty_returns"); op.drop_index("ix_warranties_company_id", table_name="warranties"); op.drop_table("warranties"); op.drop_table("service_order_deliveries"); op.drop_index("ix_service_visits_status", table_name="service_visits"); op.drop_index("ix_service_visits_service_order_id", table_name="service_visits"); op.drop_index("ix_service_visits_company_id", table_name="service_visits"); op.drop_table("service_visits"); op.drop_index("ix_service_order_work_sessions_service_order_id", table_name="service_order_work_sessions"); op.drop_index("ix_service_order_work_sessions_company_id", table_name="service_order_work_sessions"); op.drop_table("service_order_work_sessions")
