import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { api } from './api';

type Definition = { id:string;code:string;name:string;description?:string;entity_type:string;status:string;versions?:Version[] };
type Version = { id:string;workflow_definition_id:string;version_number:number;status:string;published_at?:string };
type State = { id:string;code:string;name:string;category:string;is_initial:boolean;is_terminal:boolean;is_public:boolean;position:number };
type Transition = { id:string;code:string;name:string;from_state_id:string;to_state_id:string;required_permission?:string;conditions:unknown;actions:unknown[];active:boolean };
type VersionDetail = Version & { states:State[];transitions:Transition[];validation_errors:string[] };
type Instance = { id:string;entity_type:string;entity_id:string;status:string;current_state_id:string };

function JsonInput({ label, value, onChange }: { label:string;value:string;onChange:(value:string)=>void }) {
  return <label>{label}<textarea className="mt-1 min-h-20 w-full font-mono text-xs" value={value} onChange={event=>onChange(event.target.value)} /></label>;
}

export default function Workflows() {
  const queryClient=useQueryClient();
  const [selectedDefinition,setSelectedDefinition]=useState('');
  const [selectedVersion,setSelectedVersion]=useState('');
  const [name,setName]=useState('');const [code,setCode]=useState('');
  const [stateName,setStateName]=useState('');const [stateCode,setStateCode]=useState('');const [category,setCategory]=useState('technical');const [initial,setInitial]=useState(false);const [terminal,setTerminal]=useState(false);
  const [transitionName,setTransitionName]=useState('');const [transitionCode,setTransitionCode]=useState('');const [fromState,setFromState]=useState('');const [toState,setToState]=useState('');
  const [conditions,setConditions]=useState('{}');const [actions,setActions]=useState('[]');const [error,setError]=useState('');
  const definitions=useQuery({queryKey:['workflows'],queryFn:()=>api<{items:Definition[]}>('/workflows')});
  const definition=useQuery({queryKey:['workflow',selectedDefinition],queryFn:()=>api<Definition>(`/workflows/${selectedDefinition}`),enabled:Boolean(selectedDefinition)});
  const detail=useQuery({queryKey:['workflow-version',selectedVersion],queryFn:()=>api<VersionDetail>(`/workflow-versions/${selectedVersion}`),enabled:Boolean(selectedVersion)});
  const instances=useQuery({queryKey:['workflow-instances'],queryFn:()=>api<{items:Instance[]}>('/workflow-instances')});
  const refresh=()=>{queryClient.invalidateQueries({queryKey:['workflows']});queryClient.invalidateQueries({queryKey:['workflow',selectedDefinition]});queryClient.invalidateQueries({queryKey:['workflow-version',selectedVersion]});queryClient.invalidateQueries({queryKey:['workflow-instances']})};
  const mutate=useMutation({mutationFn:({path,method='POST',body}:{path:string;method?:string;body?:unknown})=>api(path,{method,body:body===undefined?undefined:JSON.stringify(body)}),onSuccess:()=>{setError('');refresh()},onError:reason=>setError((reason as Error).message)});
  const create=()=>mutate.mutate({path:'/workflows',body:{code,name,entity_type:'service_order'}});
  const addState=()=>mutate.mutate({path:`/workflow-versions/${selectedVersion}/states`,body:{code:stateCode,name:stateName,category,is_initial:initial,is_terminal:terminal,is_public:false,position:detail.data?.states.length||0,metadata:{}}});
  const addTransition=()=>{
    try { mutate.mutate({path:`/workflow-versions/${selectedVersion}/transitions`,body:{code:transitionCode,name:transitionName,from_state_id:fromState,to_state_id:toState,required_permission:'service_order.transition',conditions:JSON.parse(conditions),actions:JSON.parse(actions),active:true,position:detail.data?.transitions.length||0}}); }
    catch { setError('Condições e ações devem conter JSON válido.'); }
  };
  return <div className="space-y-4">
    <section className="card"><h2 className="text-xl font-semibold">Workflows</h2><p className="muted">Versões publicadas são imutáveis; alterações começam por clonagem.</p><div className="mt-3 flex flex-wrap gap-2"><input aria-label="Código do workflow" placeholder="Código" value={code} onChange={event=>setCode(event.target.value)}/><input aria-label="Nome do workflow" placeholder="Nome" value={name} onChange={event=>setName(event.target.value)}/><button disabled={!code||!name} onClick={create}>Criar definição</button></div>{error&&<p role="alert" className="mt-2 text-red-700">{error}</p>}</section>
    <div className="grid gap-4 lg:grid-cols-[20rem_1fr]">
      <section className="card"><h3 className="font-semibold">Definições</h3>{definitions.isLoading&&<p>Carregando…</p>}<div className="mt-2 space-y-2">{definitions.data?.items.map(item=><button className="w-full bg-white text-left text-ink" key={item.id} onClick={()=>{setSelectedDefinition(item.id);setSelectedVersion('')}}><strong>{item.name}</strong><span className="float-right badge">{item.status}</span><span className="block muted">{item.code}</span></button>)}{definitions.data?.items.length===0&&<p className="muted">Nenhum workflow.</p>}</div></section>
      <section className="card">{!selectedDefinition?<p className="muted">Selecione uma definição.</p>:definition.data?<><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="text-lg font-semibold">{definition.data.name}</h3><p className="muted">{definition.data.code}</p></div></div><div className="mt-3 flex flex-wrap gap-2">{definition.data.versions?.map(version=><button key={version.id} className={version.id===selectedVersion?'':'bg-slate-600'} onClick={()=>setSelectedVersion(version.id)}>v{version.version_number} · {version.status}</button>)}</div>{selectedVersion&&detail.data&&<>
        <div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>mutate.mutate({path:`/workflow-versions/${selectedVersion}/validate`,method:'GET'})}>Validar grafo</button><button disabled={detail.data.status!=='draft'} onClick={()=>mutate.mutate({path:`/workflow-versions/${selectedVersion}/publish`})}>Publicar</button><button disabled={detail.data.status==='draft'} onClick={()=>mutate.mutate({path:`/workflow-versions/${selectedVersion}/clone`})}>Clonar versão</button><button disabled={detail.data.status==='published'} className="bg-slate-600" onClick={()=>confirm('Arquivar esta versão?')&&mutate.mutate({path:`/workflow-versions/${selectedVersion}/archive`})}>Arquivar</button></div>
        {detail.data.validation_errors.length>0&&<ul role="alert" className="mt-3 list-disc pl-5 text-red-700">{detail.data.validation_errors.map(value=><li key={value}>{value}</li>)}</ul>}
        <div className="mt-4 grid gap-4 xl:grid-cols-2"><div><h4 className="font-semibold">Estados</h4><table className="mt-2 w-full text-left"><thead><tr><th>Posição</th><th>Estado</th><th>Categoria</th></tr></thead><tbody>{detail.data.states.map(item=><tr className="border-t" key={item.id}><td>{item.position}</td><td>{item.name}{item.is_initial?' · inicial':''}{item.is_terminal?' · terminal':''}</td><td>{item.category}</td></tr>)}</tbody></table>{detail.data.status==='draft'&&<div className="mt-3 grid gap-2"><input aria-label="Código do estado" placeholder="Código" value={stateCode} onChange={event=>setStateCode(event.target.value)}/><input aria-label="Nome do estado" placeholder="Nome" value={stateName} onChange={event=>setStateName(event.target.value)}/><select aria-label="Categoria do estado" value={category} onChange={event=>setCategory(event.target.value)}>{['intake','triage','technical','waiting','field','delivery','closed','warranty','cancelled'].map(value=><option key={value}>{value}</option>)}</select><label><input type="checkbox" checked={initial} onChange={event=>setInitial(event.target.checked)}/> Inicial</label><label><input type="checkbox" checked={terminal} onChange={event=>setTerminal(event.target.checked)}/> Terminal</label><button disabled={!stateCode||!stateName} onClick={addState}>Adicionar estado</button></div>}</div>
        <div><h4 className="font-semibold">Transições</h4><table className="mt-2 w-full text-left"><thead><tr><th>Transição</th><th>Origem → destino</th></tr></thead><tbody>{detail.data.transitions.map(item=><tr className="border-t" key={item.id}><td>{item.name}</td><td>{detail.data?.states.find(state=>state.id===item.from_state_id)?.code} → {detail.data?.states.find(state=>state.id===item.to_state_id)?.code}</td></tr>)}</tbody></table>{detail.data.status==='draft'&&<div className="mt-3 grid gap-2"><input aria-label="Código da transição" placeholder="Código" value={transitionCode} onChange={event=>setTransitionCode(event.target.value)}/><input aria-label="Nome da transição" placeholder="Nome" value={transitionName} onChange={event=>setTransitionName(event.target.value)}/><select aria-label="Estado de origem" value={fromState} onChange={event=>setFromState(event.target.value)}><option value="">Origem</option>{detail.data.states.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select><select aria-label="Estado de destino" value={toState} onChange={event=>setToState(event.target.value)}><option value="">Destino</option>{detail.data.states.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select><JsonInput label="Condições" value={conditions} onChange={setConditions}/><JsonInput label="Ações" value={actions} onChange={setActions}/><button disabled={!transitionCode||!transitionName||!fromState||!toState} onClick={addTransition}>Adicionar transição</button></div>}</div></div>
      </>}</>:<p>Carregando definição…</p>}</section>
    </div>
    <section className="card"><h3 className="font-semibold">Instâncias recentes</h3><table className="mt-2 w-full text-left"><thead><tr><th>Entidade</th><th>Estado</th><th>Status</th></tr></thead><tbody>{instances.data?.items.map(item=><tr className="border-t" key={item.id}><td>{item.entity_type} · {item.entity_id}</td><td>{item.current_state_id}</td><td><span className="badge">{item.status}</span></td></tr>)}</tbody></table></section>
  </div>;
}
